apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore # THERE ARE TWO TYPES ClusterSecretStore and this one
    name: gcp-store # name of the SecretStore (or kind specified) refer secretstore.yaml
  target:
    name: finalsecret # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: database_username
      remoteRef:
        key: secretincloud1 # name of the GCPSM secret key
    - secretKey: database_password # this could be anything
      remoteRef:
        key: secretincloud2 # name of the GCPSM secret key
